# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[(None, None), ('M', 'Male'), ('F', 'Female')], default=None, max_length=2, null=True),
        ),
    ]
