# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_doctorprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
