# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20180702_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='document1',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='nmc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
