# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20180613_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
