# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 14:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_query', '0003_auto_20180628_1603'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('viewed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(editable=False)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_query.UserQuery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
