# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_query', '0001_initial'),
        ('notifications', '0002_auto_20180617_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='query',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users_query.UserQuery'),
            preserve_default=False,
        ),
    ]
