# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 08:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_patient', models.CharField(max_length=255)),
                ('age_of_patient', models.SmallIntegerField()),
                ('height_of_patient', models.CharField(blank=True, max_length=8)),
                ('weight_of_patient', models.SmallIntegerField(blank=True)),
                ('title_problem', models.CharField(max_length=510)),
                ('description', models.TextField()),
                ('tag', models.CharField(choices=[('S', 'skin'), ('E', 'ent'), ('P', 'Physician')], max_length=1)),
                ('date_of_submission', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
