# Generated by Django 2.0.5 on 2018-06-10 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users_query.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointed_doc', models.CharField(max_length=25)),
                ('appointed_time', models.DateTimeField()),
                ('hospital', models.CharField(max_length=25)),
                ('venue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_medicine', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('times_a_day', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('prescribed_date', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ManyToManyField(to='users_query.Medicine')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_patient', models.CharField(max_length=255)),
                ('age_of_patient', models.SmallIntegerField()),
                ('height_of_patient', models.CharField(blank=True, max_length=8)),
                ('weight_of_patient', models.SmallIntegerField(blank=True, null=True)),
                ('title_problem', models.CharField(max_length=510)),
                ('description', models.TextField()),
                ('file_related', models.FileField(blank=True, null=True, upload_to=users_query.models.get_file_path)),
                ('tag', models.CharField(choices=[('S', 'skin'), ('E', 'ent'), ('P', 'Physician')], max_length=1)),
                ('date_of_submission', models.DateTimeField(auto_now_add=True)),
                ('taken', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_query.UserQuery'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_query.UserQuery'),
        ),
    ]
