# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 08:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='date_of_submission',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='height_of_patient',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='weight_of_patient',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
