# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_query', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicine',
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine',
            field=models.ManyToManyField(to='users_query.Medicine'),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
