# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_query', '0002_auto_20180621_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquery',
            name='prescription',
        ),
        migrations.AddField(
            model_name='prescription',
            name='query',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users_query.UserQuery'),
            preserve_default=False,
        ),
    ]
