# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_query', '0002_auto_20180628_1507'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Picture',
            new_name='File',
        ),
    ]
