# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 08:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_query', '0002_auto_20180603_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='height_of_patient',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
