# Generated by Django 2.0 on 2018-06-21 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_query', '0003_auto_20180621_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquery',
            name='appointment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='query',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users_query.UserQuery'),
            preserve_default=False,
        ),
    ]
