# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 11:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_query', '0004_userquery_taken_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='taken_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
