# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 12:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_query', '0005_auto_20180702_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
