# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_query', '0006_auto_20180702_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='tag',
            field=models.CharField(choices=[('S', 'General Surgery'), ('G', 'Obesterics and Gynecology'), ('P', 'General Physician'), ('Or', 'Orthopedic'), ('D', 'Dermatology & Venerology'), ('A', 'Anesthesiology'), ('N', 'Nephrology'), ('Ps', 'Psychiatry'), ('M', 'General Medicine'), ('On', 'Oncology'), ('Pd', 'Paediatrics'), ('E', 'Ear Nose Throat'), ('O', 'Opthalmology'), ('De', 'Dental Surgeon'), ('T', 'Physiotherapy')], max_length=2),
        ),
    ]
