# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-14 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_query', '0006_auto_20180702_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointed_doc',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hospital',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='venue',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name_of_medicine',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='times_a_day',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='title_problem',
            field=models.CharField(max_length=511),
        ),
    ]
