# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_query', '0007_auto_20180713_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.CharField(max_length=350),
        ),
    ]
