# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-14 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_query', '0008_auto_20180714_1258'),
        ('users_query', '0008_auto_20180713_1316'),
    ]

    operations = [
    ]
