# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-01-16 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_query', '0009_merge_20180714_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='height_of_patient',
            field=models.FloatField(blank=True, max_length=8),
        ),
    ]
