export const AuthTypes = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',

    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',

    SIGNUP_RESEND_FAILURE: 'SIGNUP_RESEND_FAILURE',

    VERIFY_EMAIL_ERROR: 'VERIFY_EMAIL_ERROR',

    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD',
    RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_ERROR',
    VERIFY_RESET_PASSWORD_SUCCESS: 'VERIFY_RESET_PASSWORD_SUCCESS',
    VERIFY_RESET_PASSWORD_FAILURE: 'VERIFY_RESET_PASSWORD_FAILURE',

    AUTH_USER: 'AUTH_USER',
    UNAUTH_USER: 'UNAUTH_USER',

    FETCH_USERS: 'FETCH_USERS',
};
