# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date_time',
            new_name='created',
        ),
    ]
